---
name: BATS Tests

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        run: make tests